# Generated by Django 2.0 on 2022-12-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_auto_20221113_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='optionSiNo',
            field=models.BooleanField(default=False, help_text='Marca esta casilla para que las opciones sean Si o No. No podrás añadir más opciones'),
        ),
        migrations.AddField(
            model_name='voting',
            name='seats',
            field=models.PositiveIntegerField(default=0, help_text='Introduzca número de escaños a repartir en caso de elegir DHONT'),
        ),
        migrations.AddField(
            model_name='voting',
            name='typepostproc',
            field=models.CharField(choices=[('IDENTITY', 'IDENTITY'), ('DHONT', 'DHONT')], default='IDENTITY', help_text='Método de recuento', max_length=8),
        ),
    ]
