# Generated by Django 2.0 on 2022-11-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_auto_20221113_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='sino',
            field=models.BooleanField(default=False, help_text='Márcala si quieres que las respuestas sean Si/No. No se podrán añadir mas respuestas'),
        ),
    ]
