# Generated by Django 2.0 on 2022-12-14 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_question_optionsino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='optionSiNo',
        ),
    ]
