# Generated by Django 2.0 on 2022-12-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_question_sino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='sino',
        ),
        migrations.AddField(
            model_name='question',
            name='optionSiNo',
            field=models.BooleanField(default=False, help_text='Marca esta casilla para que las respuestas sean Si o No. No podrás añadir más respuestas después'),
        ),
    ]
