# Generated by Django 2.0 on 2022-12-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_question_optionsino'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='seats',
            field=models.PositiveIntegerField(default=0, help_text='Introduzca número de escaños a repartir en caso de elegir DHONT'),
        ),
        migrations.AddField(
            model_name='voting',
            name='typePostproc',
            field=models.CharField(choices=[('IDENTITY', 'IDENTITY'), ('DHONT', 'DHONT')], default='IDENTITY', help_text='Elige método de recuento', max_length=8),
        ),
    ]
