# Generated by Django 2.0 on 2022-12-13 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_auto_20221213_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voting',
            old_name='typePostproc',
            new_name='typepostproc',
        ),
    ]
