# Generated by Django 2.0 on 2022-12-14 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_auto_20221213_2104'),
        ('voting', '0007_question_optionsino'),
    ]

    operations = [
    ]
